# Stop all the servers
---
  - hosts: loadbalancer
    become: true
    tasks:
       - name: Ensure nginx is stopped
         service: name=nginx state=restarted

  - hosts: webserver
    become: true
    tasks:
       - name: Ensure apache2 is stopped
         service: name=apache2 state=restarted

  - hosts: database
    become: true                             
    tasks:
       - name: Ensure mysql is stopped
         service: name=mysql state=restarted

